schema = 3

[mod]
  [mod.'charm.land/lipgloss/v2']
    version = 'v2.0.0-beta.3.0.20251125170225-454007a0ad4e'
    hash = 'sha256-4MUPUz/xcPuC3kYEzl+v6CEgDhUM+mUe7qZeB39o2RI='

  [mod.'github.com/Nadim147c/fang']
    version = 'v1.1.1'
    hash = 'sha256-Y+SSgvjG9IPIbfJ/45dcK+Ht31ZxZ8dcWbuyuw6Fwr8='

  [mod.'github.com/Nadim147c/real-go']
    version = 'v0.0.0-20260320162608-66134fbe4e77'
    hash = 'sha256-Q6Q5eLzW7La9BfOks68YueNxYplID2wHagq4BZkSyas='

  [mod.'github.com/adrg/xdg']
    version = 'v0.5.3'
    hash = 'sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/charmbracelet/bubbles']
    version = 'v1.0.0'
    hash = 'sha256-Vz9QgctlzJqggPwfi48Lbn38ZJXu3Y71byp5uuuzUvU='

  [mod.'github.com/charmbracelet/bubbletea']
    version = 'v1.3.10'
    hash = 'sha256-7wr85TLszu1CHNEMv+o4w+r24Z0xdzCgecPv+ZtRX/A='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.1'
    hash = 'sha256-d/NjM/ybG+bGRRRMMcjbPCFGFS5noZRMaL05Ix5r/II='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.0'
    hash = 'sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4='

  [mod.'github.com/charmbracelet/log']
    version = 'v1.0.0'
    hash = 'sha256-Veo9gqSs/ZHFNERzXSCtQjovaIwdr8YZkCIJ7xfTEGY='

  [mod.'github.com/charmbracelet/ultraviolet']
    version = 'v0.0.0-20260113215839-fa031ff101a1'
    hash = 'sha256-12kEM9wA+Rl5YXjry1HrrSeg0OQcY2OxzpvxWYZQF6Y='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.6'
    hash = 'sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI='

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.15'
    hash = 'sha256-0S60XaWhKZG+TB3Kqe1oMn2Okwdq53nym8XayVSHHiM='

  [mod.'github.com/charmbracelet/x/exp/charmtone']
    version = 'v0.0.0-20260113142046-c1fa3de7983b'
    hash = 'sha256-Q6ouXSvCucqKj3S7J0r7lyxQ1NpiuF80mgkmgnvtvMw='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

  [mod.'github.com/charmbracelet/x/termios']
    version = 'v0.1.1'
    hash = 'sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds='

  [mod.'github.com/charmbracelet/x/windows']
    version = 'v0.2.2'
    hash = 'sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk='

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.9.0'
    hash = 'sha256-9CNyTZPSncKQ7Y0my9DR4WYXDjtDHYNL512D691WDAM='

  [mod.'github.com/clipperhouse/stringish']
    version = 'v0.1.1'
    hash = 'sha256-Mp8M1CRbwr6dcJ4BD9tXD5I78ZgCFEm0GDxJv0GYReg='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.5.0'
    hash = 'sha256-Men4JLhiuEtAx8ZSzId5ciRWhud68o3k/B48ppwyxkM='

  [mod.'github.com/erikgeiser/coninput']
    version = 'v0.0.0-20211004153227-1c3628e74d0f'
    hash = 'sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU='

  [mod.'github.com/go-logfmt/logfmt']
    version = 'v0.6.1'
    hash = 'sha256-+gUGmdR/QOsB9qKESLrsbq6tK2VssNT/kDbRFpgrZL4='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.3.0'
    hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mattn/go-localereader']
    version = 'v0.0.1'
    hash = 'sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.19'
    hash = 'sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE='

  [mod.'github.com/muesli/ansi']
    version = 'v0.0.0-20230316100256-276c6243b2f6'
    hash = 'sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/muesli/mango']
    version = 'v0.2.0'
    hash = 'sha256-hEu9ZE2yYBCD2O9KNq8Lgc8dGeCPrTgx/b0tZtTToJk='

  [mod.'github.com/muesli/mango-cobra']
    version = 'v1.3.0'
    hash = 'sha256-VPE2A9eyMI63789PcnM5Ltm5PWt/yewWVh7hKtyoe4c='

  [mod.'github.com/muesli/mango-pflag']
    version = 'v0.2.0'
    hash = 'sha256-gF9oIQpH9iGFEzDOrfgurtVOd1BjGmSRMkNDnSJClcw='

  [mod.'github.com/muesli/roff']
    version = 'v0.1.0'
    hash = 'sha256-0A/M8h0+dSF1NruiGjs4WbfWENFbV3VpyIwJzHEeRlA='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20231006140011-7918f672742d'
    hash = 'sha256-2SO1etTQ6UCUhADR5sgvDEDLHcj77pJKCIa/8mGDbAo='

  [mod.'golang.org/x/sync']
    version = 'v0.19.0'
    hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

  [mod.'golang.org/x/sys']
    version = 'v0.40.0'
    hash = 'sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg='

  [mod.'golang.org/x/text']
    version = 'v0.33.0'
    hash = 'sha256-XdA6D39ESuJkaaM/SRBnqZzjKUwi6Gbt1Si1nvauTr4='
